ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
endif::[]

:toc:
:toc-placement!:

= Mobile Developer Console - Standard Operating Procedures

:toc:
toc::[]

== Overview

The following guide outlines the steps required to manage and solve issues in the https://github.com/aerogear/mobile-developer-console[Mobile Developer Console] which is managed, installed and configured via the https://github.com/aerogear/mobile-developer-console-operator[Mobile Developer Console Operator].

== Reference Articles

- https://github.com/aerogear/mobile-developer-console[Mobile Developer Console]
- https://github.com/aerogear/mobile-developer-console-operator[Mobile Developer Console Operator]
- https://prometheus.io/docs/practices/alerting/[Prometheus Alerts documentation]

== Success Indicators

All alerts should appear as green in the Prometheus Alert Monitoring.

== Prometheus Alerts Procedures

IMPORTANT: Before checking any of following steps see if the operator pod is running successfully. More info: link:./SOP-operator.adoc[MobileDeveloperConsoleOperatorDown]

TIP: Logs can be saved by running `oc logs <podname> > <filename>.log`. The logs can provide useful information in order to identify the root cause of the issue. They may also contain useful information which should be included when creating any issues against the project for maintainers to check.

=== Critical

==== MobileDeveloperConsoleDown or MobileDeveloperConsoleContainerDown

. Switch to the Mobile Developer Console namespace by running `oc project <namespace>`. E.g `oc project mobile-developer-console`.
. Follow the <<Validate>> steps.

. Verify the MobileDeveloperConsole is deployed in the same namespace as the operator.
.. Run `oc get MobileDeveloperConsole`
+
Expected results:
----
$ oc project mobile-developer-console
$ oc get MobileDeveloperConsole
NAME          PHASE
example-mdc
----

. Verify that the OAuthProxy Container is running successfully.
+
.. Run `oc logs <service-podname> -c mdc-oauth-proxy`. E.g `oc logs example-mdc-1-8m5ql -c mdc-oauth-proxy`
+

Logs should include the following:
+
----
2019/08/01 09:39:04 oauthproxy.go:201: mapping path "/" => upstream "http://localhost:4000/"
2019/08/01 09:39:04 oauthproxy.go:228: OAuthProxy configured for  Client ID: mobile-developer-console
2019/08/01 09:39:04 oauthproxy.go:238: Cookie settings: name:_oauth_proxy secure(https):true httponly:false expiry:168h0m0s domain:<default> refresh:disabled
2019/08/01 09:39:04 http.go:56: HTTP: listening on 0.0.0.0:4180
----
+

.. If alternative logs are found in the above step then save the logs by running `oc logs <service-podname> -c mdc-oauth-proxy > <filename>.log`

=== Warning

==== MobileDeveloperConsolePodCPUHigh

This alert indicates that the Service pod(s) is/are using more CPU than expected.

. Please follow the <<To capture the logs>> procedure in order to capture the required information to send it to its maintainers.
. Please follow the <<To scale the pod>> procedure in order to try to solve performance issues.

==== MobileDeveloperConsolePodMemoryHigh

This alert indicates that the Service pod(s) is/are using more Memory than expected.

. Please follow the <<To capture the logs>> procedure in order to capture the required information to send it to its maintainers.
. Please follow the <<To scale the pod>> procedure in order to try to solve performance issues.


==== To capture the logs

. Capture a snapshot of the 'Mobile Developer Console Application' Grafana dashboard and track it over time. The metrics can be useful for identifying performance issues over time.
. Capture the Service logs
.. Get the pod names by running `oc get pods`
.. Save the logs by running `oc logs <mdc-podname> > <filename>.log` for any pod
. Capture CR Status by running `oc describe MobileDeveloperConsole`.

==== To scale the pod

. Scale the Mobile Develper Console pod
.. Check the number of DESIRED and CURRENT replicas, and make sure that they're the same:
----
oc get deploymentconfig --selector='app=mdc'
NAME      REVISION   DESIRED   CURRENT   TRIGGERED BY
mdc       3          1         1         config,image(mdc-imagestream:1.1.4),image(mdc-oauth-proxy-imagestream:latest)
----
If they're not, this may indicate a problem with the ability to scale up (capacity, missing images, etc), or the ability to scale down (a node where a pod was scheduled might be in trouble etc.).
.. Scale the replication controller if more pods are desired by running `oc scale deploymentconfig --selector='app=mdc' --replicas=X` where X is the number of desired pods.

== Validate

=== Installation

Follow these steps to ensure that the installation completed as expected.

. Switch to the Mobile Developer Console namespace by running `oc project <namespace>`  E.g `oc project mobile-developer-console`.
. Check that the link:./deploy/crds/mdc_v1alpha1_mobiledeveloperconsole_cr.yaml[MobileDeveloperConsole CR] is deployed in the same namespace as the operator by running `oc get MobileDeveloperConsole`.
+
[source,shell]
----
$ oc get MobileDeveloperConsole
NAME                        AGE
mdc                         9d
----
+
IMPORTANT: This CR instructs the operator to install and configure Service pods. If there is any issues with the creation of any of the following resources the logs of the operator should be checked for relevant errors.
+
TIP: Logs can be saved by running `oc logs <podname> > <filename>.log`. The logs can provide useful information in order to identify the root cause of the issue. They may also contain useful information which should be included when creating any issues against the project for maintainers to check.
+
. Check that there are at least 2 pods running in the namspace (Server and Operator) by running `oc get pods`. 
+
----
$ oc get pods
NAME                                                    READY     STATUS    RESTARTS   AGE
mdc-6-glhzb                                             1/1       Running   2          12d
mobile-developer-console-operator-b6d447bcf-c7qfl       1/1       Running   6          12d
----
+
. Check that the image streams for the Service and Oauth Proxy were created with success by running `oc get imagestream`. 
+
[source,shell]
----
$ oc get imagestream
NAME                          DOCKER REPO                                                                               TAGS      UPDATED
mdc-imagestream               docker-registry.default.svc:5000/mobile-developer-console/mdc-imagestream                 latest    12 days ago
mdc-oauth-proxy-imagestream   docker-registry.default.svc:5000/mobile-developer-console/mdc-oauth-proxy-imagestream     latest    12 days ago
----
+
. Check that the route to expose the service was created successfully by running `oc get route | grep mdc-mdc-proxy`. 
+
[source,shell]
----
$ oc get route | grep mdc-mdc-proxy
mdc-mdc-proxy   https://<route-name>-mobile-developer-console.apps.<cluster-route>             mdc-mdc-proxy   <all>     edge/None     None
----
. Check that the DeploymentConfig to deploy the Service was created successfully by running `oc get deploymentconfig | grep mdc`.  
+
[source,shell]
----
$ oc get deploymentconfig | grep mdc
mdc   1          2         2         config,image(mdc-imagestream:1.1.1),image(mdc-oauth-proxy-imagestream:latest)
----
+
. Check that there are 3 Services created in the namespace, one for the service, one for the OAuth proxy and one for the operator
+
[source,shell]
----
$ oc get service | grep proxy
NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
mdc-mdc                             ClusterIP   172.30.38.217   <none>        80/TCP     12d
mdc-mdc-proxy                       ClusterIP   172.30.77.150   <none>        80/TCP     12d
mobile-developer-console-operator   ClusterIP   172.30.205.34   <none>        8383/TCP   12d
----
+

=== Optional configurations

==== Monitor

If the https://github.com/aerogear/mobile-developer-console-operator#monitoring-service-metrics[Monitoring Service (Metrics)] is enabled for the installation, a Grafana Dashboard titled `MDC Application`, and the Prometheus Monitoring instance are created.

